

public class MainUI extends javax.swing.JFrame {

    /** Creates new form MainUI */
    public MainUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuLib = new javax.swing.JMenuItem();
        mnuLibEdit = new javax.swing.JMenuItem();
        mnuIssue = new javax.swing.JMenuItem();
        mnuReturn = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuPub = new javax.swing.JMenuItem();
        mnuPMod = new javax.swing.JMenuItem();
        mnuPDel = new javax.swing.JMenuItem();
        mnuPNav = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuMemb = new javax.swing.JMenuItem();
        mnuMMod = new javax.swing.JMenuItem();
        mnuMDel = new javax.swing.JMenuItem();
        mnuMNav = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuABList = new javax.swing.JMenuItem();
        mnuIBList = new javax.swing.JMenuItem();
        mnuMList = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setBounds(new java.awt.Rectangle(200, 70, 0, 0));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library Application");

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 30));
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Library Management System");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e-library2.jpg"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu2.setText("Book");

        mnuLib.setText("Book Console");
        mnuLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLib);

        mnuLibEdit.setText("Modification");
        mnuLibEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibEditActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLibEdit);

        mnuIssue.setText("Book Issue");
        mnuIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIssueActionPerformed(evt);
            }
        });
        jMenu2.add(mnuIssue);

        mnuReturn.setText("Book Return");
        mnuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReturnActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReturn);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Publisher");

        mnuPub.setText("Publisher Console");
        mnuPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPubActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPub);

        mnuPMod.setText("Modification");
        mnuPMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPModActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPMod);

        mnuPDel.setText("Deletion");
        mnuPDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPDelActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPDel);

        mnuPNav.setText("Record Navigation");
        mnuPNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPNavActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPNav);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Member");

        mnuMemb.setText("Member Console");
        mnuMemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMembActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMemb);

        mnuMMod.setText("Modification");
        mnuMMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMModActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMMod);

        mnuMDel.setText("Deletion");
        mnuMDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMDelActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMDel);

        mnuMNav.setText("Navigation");
        mnuMNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMNavActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMNav);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Report");

        mnuABList.setText("Available Book List");
        mnuABList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuABListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuABList);

        mnuIBList.setText("Issued Book List");
        mnuIBList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIBListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuIBList);

        mnuMList.setText("Member List");
        mnuMList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuMList);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quit");

        mnuQuit.setText("Application");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });
        jMenu5.add(mnuQuit);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-820)/2, (screenSize.height-568)/2, 820, 568);
    }// </editor-fold>//GEN-END:initComponents
    private void mnuPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPubActionPerformed
        //this.setVisible(false);
        new pubUI().setVisible(true);  dispose();
        new pubUI().getAlignmentX();
        
    }//GEN-LAST:event_mnuPubActionPerformed

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuQuitActionPerformed

    private void mnuPModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPModActionPerformed
        new PubEditUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuPModActionPerformed

    private void mnuPDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPDelActionPerformed
        new PubDelUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuPDelActionPerformed

    private void mnuPNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPNavActionPerformed
        new PubNavUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuPNavActionPerformed

    private void mnuLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibActionPerformed
        new LibUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuLibActionPerformed

    private void mnuMembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMembActionPerformed
        new MembUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuMembActionPerformed

    private void mnuMModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMModActionPerformed
        new MembEditUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuMModActionPerformed

    private void mnuMDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMDelActionPerformed
        new MembDelUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuMDelActionPerformed

    private void mnuMNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMNavActionPerformed
        new MembNavUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuMNavActionPerformed

    private void mnuIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIssueActionPerformed
        new IssueUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuIssueActionPerformed

    private void mnuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReturnActionPerformed
        new ReturnUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuReturnActionPerformed

    private void mnuABListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuABListActionPerformed
        new ABListUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuABListActionPerformed

    private void mnuIBListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIBListActionPerformed
        new IBListUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuIBListActionPerformed

    private void mnuMListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMListActionPerformed
        new MListUI().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuMListActionPerformed

    private void mnuLibEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibEditActionPerformed
new LibEditUI().setVisible(true);      dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_mnuLibEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
                

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem mnuABList;
    private javax.swing.JMenuItem mnuIBList;
    private javax.swing.JMenuItem mnuIssue;
    private javax.swing.JMenuItem mnuLib;
    private javax.swing.JMenuItem mnuLibEdit;
    private javax.swing.JMenuItem mnuMDel;
    private javax.swing.JMenuItem mnuMList;
    private javax.swing.JMenuItem mnuMMod;
    private javax.swing.JMenuItem mnuMNav;
    private javax.swing.JMenuItem mnuMemb;
    private javax.swing.JMenuItem mnuPDel;
    private javax.swing.JMenuItem mnuPMod;
    private javax.swing.JMenuItem mnuPNav;
    private javax.swing.JMenuItem mnuPub;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JMenuItem mnuReturn;
    // End of variables declaration//GEN-END:variables
}